from typing import Protocol

class SocialConnector(Protocol):
    """Protocol for social media connectors"""
    def connect_account(self) -> bool: ...
    def refresh_token(self) -> bool: ...
    def publish_post(self, content: str) -> dict: ...
    def get_post(self, post_id: str) -> dict: ...
    def get_analytics(self) -> dict: ...
    def get_comments(self) -> list: ...
    def reply_to_comment(self, comment_id: str, text: str) -> bool: ...
