"""schema fixes

Revision ID: 006_schema_fixes
Revises: 005_email_refinement
Create Date: 2026-08-11 10:00:00.000000

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '006_schema_fixes'
down_revision = '005_email'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # Rename base_text to base_content
    op.alter_column('content_items', 'base_text', new_column_name='base_content')

    # Drop obsolete brand_profile_id from social_accounts
    # Need to drop foreign key constraint first if one exists
    # Alembic's drop_constraint requires the exact name
    # We will execute a raw SQL to drop the foreign key since its name might be autogenerated
    # If we created it without a name in 001_initial: sa.ForeignKey('brand_profiles.id')
    # PostgreSQL autogenerates something like social_accounts_brand_profile_id_fkey
    op.execute(
        "ALTER TABLE social_accounts DROP CONSTRAINT IF EXISTS social_accounts_brand_profile_id_fkey"
    )
    op.drop_column('social_accounts', 'brand_profile_id')

def downgrade() -> None:
    # Re-add brand_profile_id
    op.add_column('social_accounts', sa.Column('brand_profile_id', sa.Integer(), nullable=True))
    op.create_foreign_key(
        'social_accounts_brand_profile_id_fkey',
        'social_accounts',
        'brand_profiles',
        ['brand_profile_id'],
        ['id']
    )

    # Rename base_content to base_text
    op.alter_column('content_items', 'base_content', new_column_name='base_text')
