"""fix missing columns

Revision ID: 2f164f7dff9b
Revises: 006_schema_fixes
Create Date: 2026-08-11 17:06:32.659155

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '2f164f7dff9b'
down_revision = '006_schema_fixes'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(op.f('ai_insights_organization_id_fkey'), 'ai_insights', type_='foreignkey')
    op.create_foreign_key(None, 'ai_insights', 'organizations', ['organization_id'], ['id'], ondelete='CASCADE')
    op.drop_constraint(op.f('analytics_snapshots_organization_id_fkey'), 'analytics_snapshots', type_='foreignkey')
    op.create_foreign_key(None, 'analytics_snapshots', 'organizations', ['organization_id'], ['id'], ondelete='CASCADE')
    op.drop_constraint(op.f('audiences_organization_id_fkey'), 'audiences', type_='foreignkey')
    op.create_foreign_key(None, 'audiences', 'organizations', ['organization_id'], ['id'], ondelete='CASCADE')
    op.drop_constraint(op.f('audit_logs_user_id_fkey'), 'audit_logs', type_='foreignkey')
    op.drop_constraint(op.f('audit_logs_organization_id_fkey'), 'audit_logs', type_='foreignkey')
    op.create_foreign_key(None, 'audit_logs', 'users', ['user_id'], ['id'], ondelete='SET NULL')
    op.create_foreign_key(None, 'audit_logs', 'organizations', ['organization_id'], ['id'], ondelete='CASCADE')
    op.drop_constraint(op.f('brand_profiles_organization_id_fkey'), 'brand_profiles', type_='foreignkey')
    op.create_foreign_key(None, 'brand_profiles', 'organizations', ['organization_id'], ['id'], ondelete='CASCADE')
    op.drop_constraint(op.f('campaigns_organization_id_fkey'), 'campaigns', type_='foreignkey')
    op.create_foreign_key(None, 'campaigns', 'organizations', ['organization_id'], ['id'], ondelete='CASCADE')
    op.drop_constraint(op.f('content_items_campaign_id_fkey'), 'content_items', type_='foreignkey')
    op.create_foreign_key(None, 'content_items', 'campaigns', ['campaign_id'], ['id'], ondelete='CASCADE')
    op.drop_constraint(op.f('email_campaigns_organization_id_fkey'), 'email_campaigns', type_='foreignkey')
    op.create_foreign_key(None, 'email_campaigns', 'organizations', ['organization_id'], ['id'], ondelete='CASCADE')
    op.drop_index(op.f('ix_engagement_items_category'), table_name='engagement_items')
    op.drop_index(op.f('ix_engagement_items_sentiment'), table_name='engagement_items')
    op.drop_constraint(op.f('engagement_items_published_post_id_fkey'), 'engagement_items', type_='foreignkey')
    op.create_foreign_key(None, 'engagement_items', 'published_posts', ['published_post_id'], ['id'], ondelete='CASCADE')
    op.drop_constraint(op.f('platform_variants_content_item_id_fkey'), 'platform_variants', type_='foreignkey')
    op.create_foreign_key(None, 'platform_variants', 'content_items', ['content_item_id'], ['id'], ondelete='CASCADE')
    op.add_column('published_posts', sa.Column('platform_variant_id', sa.Integer(), nullable=True))
    op.drop_constraint(op.f('published_posts_schedule_id_fkey'), 'published_posts', type_='foreignkey')
    op.create_foreign_key(None, 'published_posts', 'platform_variants', ['platform_variant_id'], ['id'], ondelete='SET NULL')
    op.create_foreign_key(None, 'published_posts', 'schedules', ['schedule_id'], ['id'], ondelete='SET NULL')
    op.drop_constraint(op.f('schedules_platform_variant_id_fkey'), 'schedules', type_='foreignkey')
    op.create_foreign_key(None, 'schedules', 'platform_variants', ['platform_variant_id'], ['id'], ondelete='CASCADE')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'schedules', type_='foreignkey')
    op.create_foreign_key(op.f('schedules_platform_variant_id_fkey'), 'schedules', 'platform_variants', ['platform_variant_id'], ['id'])
    op.drop_constraint(None, 'published_posts', type_='foreignkey')
    op.drop_constraint(None, 'published_posts', type_='foreignkey')
    op.create_foreign_key(op.f('published_posts_schedule_id_fkey'), 'published_posts', 'schedules', ['schedule_id'], ['id'])
    op.drop_column('published_posts', 'platform_variant_id')
    op.drop_constraint(None, 'platform_variants', type_='foreignkey')
    op.create_foreign_key(op.f('platform_variants_content_item_id_fkey'), 'platform_variants', 'content_items', ['content_item_id'], ['id'])
    op.drop_constraint(None, 'engagement_items', type_='foreignkey')
    op.create_foreign_key(op.f('engagement_items_published_post_id_fkey'), 'engagement_items', 'published_posts', ['published_post_id'], ['id'])
    op.create_index(op.f('ix_engagement_items_sentiment'), 'engagement_items', ['sentiment'], unique=False)
    op.create_index(op.f('ix_engagement_items_category'), 'engagement_items', ['category'], unique=False)
    op.drop_constraint(None, 'email_campaigns', type_='foreignkey')
    op.create_foreign_key(op.f('email_campaigns_organization_id_fkey'), 'email_campaigns', 'organizations', ['organization_id'], ['id'])
    op.drop_constraint(None, 'content_items', type_='foreignkey')
    op.create_foreign_key(op.f('content_items_campaign_id_fkey'), 'content_items', 'campaigns', ['campaign_id'], ['id'])
    op.drop_constraint(None, 'campaigns', type_='foreignkey')
    op.create_foreign_key(op.f('campaigns_organization_id_fkey'), 'campaigns', 'organizations', ['organization_id'], ['id'])
    op.drop_constraint(None, 'brand_profiles', type_='foreignkey')
    op.create_foreign_key(op.f('brand_profiles_organization_id_fkey'), 'brand_profiles', 'organizations', ['organization_id'], ['id'])
    op.drop_constraint(None, 'audit_logs', type_='foreignkey')
    op.drop_constraint(None, 'audit_logs', type_='foreignkey')
    op.create_foreign_key(op.f('audit_logs_organization_id_fkey'), 'audit_logs', 'organizations', ['organization_id'], ['id'])
    op.create_foreign_key(op.f('audit_logs_user_id_fkey'), 'audit_logs', 'users', ['user_id'], ['id'])
    op.drop_constraint(None, 'audiences', type_='foreignkey')
    op.create_foreign_key(op.f('audiences_organization_id_fkey'), 'audiences', 'organizations', ['organization_id'], ['id'])
    op.drop_constraint(None, 'analytics_snapshots', type_='foreignkey')
    op.create_foreign_key(op.f('analytics_snapshots_organization_id_fkey'), 'analytics_snapshots', 'organizations', ['organization_id'], ['id'])
    op.drop_constraint(None, 'ai_insights', type_='foreignkey')
    op.create_foreign_key(op.f('ai_insights_organization_id_fkey'), 'ai_insights', 'organizations', ['organization_id'], ['id'])
    # ### end Alembic commands ###
